### PR TITLE
bazel: add python depenencies to vppapigen

### PR DESCRIPTION
**Pull request by sgmonroy**
This change is [Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6)

### CODE REVIEW

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6)* status: all files reviewed, 1 unresolved discussion (waiting on @sgmonroy)

___
*[deps.bzl, line 6 at r2](https://reviewable.io/reviews/anapaya/vpp-build/6#-M1WOa-OEh5BDA5a2V4X:-M1WOa-P7Iu4kQ-JFEh1:b-k10qpq) ([raw file](https://github.com/anapaya/vpp-build/blob/46ac5a258112251707c50a4e6c86a181351dd843/deps.bzl#L6)):*
> ```Starlark
> def vpp_deps():
>     py_repositories()
>     
> ```

extra spaces

**Review by sgmonroy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[deps.bzl, line 6 at r2](https://reviewable.io/reviews/anapaya/vpp-build/6#-M1WOa-OEh5BDA5a2V4X:-M1Zcin0EPQinMRfIVlj:b-896fix) ([raw file](https://github.com/anapaya/vpp-build/blob/46ac5a258112251707c50a4e6c86a181351dd843/deps.bzl#L6)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

extra spaces
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sustrik — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/anapaya/vpp-build/6#-:-M1ZgYJu1ObdtaHnazk5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sustrik)

**Pull request merged**
